name: Build and Publish Flutter Image

on:
  workflow_dispatch:
    inputs:
      flutter_version:
        description: 'Flutter version/branch to use'
        default: 'stable'
        required: false
        type: string
      image_tag:
        description: 'Version tag (e.g. v1.2.3)'
        default: 'v0.0.1'
        required: false
        type: string
      dockerfile_path:
        description: 'Path to Dockerfile'
        default: 'infra/docker/Dockerfile'
        required: false
        type: string
  # push:
  #   branches: [ main, master ]
  #   paths:
  #     - 'docker/**'

env:
  REGISTRY: ${{ secrets.DOCKER_REGISTRY || 'docker.io' }}
  IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME || 'flutter-container' }}
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag from version and date
        id: version_tag
        run: |
          VERSION_INPUT="${{ github.event.inputs.image_tag }}"
          DATE=$(date +'%d-%m-%Y')
          FULL_TAG="${VERSION_INPUT}-${DATE}"
          echo "tag=$FULL_TAG" >> $GITHUB_OUTPUT

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.version_tag.outputs.tag }}
            type=sha,format=short
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ github.event.inputs.dockerfile_path || './docker/Dockerfile' }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          platforms: ${{ env.PLATFORMS }}
          build-args: |
            FLUTTER_VERSION=${{ github.event.inputs.flutter_version || 'stable' }}

      # Temp fix for https://github.com/docker/build-push-action/issues/252
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
